# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  Default

steps:
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
      
#- task: UiPathRunJob@2
#  inputs:
#    orchestratorConnection: 'Uipath_Testing'
#    processName: 'Azure_Demo'
#    folderName: 'Modren Example'
#    user: 'uipath\balamanikanta.krishn'
#- task: UseDotNet@2
#  inputs:
#    packageType: 'sdk'
#    version: '6.0.7'
- task: UiPathInstallPlatform@4
  inputs:
    cliVersion: 'WIN_23.4.8951.9936'
- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: 'C:\Users\balamanikanta.krishn\Downloads\LIBRARY_CL_SendOutlookEmail\project.json'
    outputType: 'Library'
    orchestratorConnection: 'UipathOrch'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
#- task: UiPathPack@4
#  inputs:
#    versionType: 'AutoVersion'
#    projectJsonPath: 'C:\Users\balamanikanta.krishn\Downloads\LIBRARY_CL_SendOutlookEmail\project.json'
#    outputType: 'Process'
#    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
#    orchestratorConnection: 'UipathOrch'
- task: UiPathDeploy@2
  inputs:
    orchestratorConnection: 'UipathOrch'
    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
    folderName: 'Test'
- task: UiPathAssets@2
  inputs:
    orchestratorConnection: 'UipathOrch'
    folderName: 'Test'
    assetActionType: 'Deploy'
    csvFile: 'C:\agent\_work\2\s\test.csv'
- task: UiPathTest@2
  inputs:
    testTarget: 'TestProject'
    orchestratorConnection: 'UipathOrch'
    folderName: 'Test'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
#- task: UiPathDeploy@2
#  inputs:
#    orchestratorConnection: 'Uipath_Testing'
#    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
#    folderName: 'Test'
#    entryPoints: 'Main.xaml'