# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  Default

steps:
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
      
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '20.x'
- task: UiPathInstallPlatform@5
  inputs:
    cliVersion: 'WIN_24.10.9050.17872'
- task: DownloadPackage@1
  inputs:
    packageType: 'nuget'
    feed: '7eff2d39-89ec-455f-9dcd-3610dfbf0507/c3c48568-0c03-47a7-85ff-3593837585a4'
    view: '745595e6-41f7-4661-ab14-6f538f640c92'
    definition: 'b5dc1268-9a57-4fbb-858d-2984fdf9846a'
    version: '23.4.8951.9936'
    extract: true
    downloadPath: '$(System.ArtifactsDirectory)\CLI'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # UiPath Pack Task
      $cliPath = "$(System.ArtifactsDirectory)\CLI\tools\uipcli.exe"
      & $cliPath package pack "$(Build.SourcesDirectory)\project.json" -o "$(Build.SourcesDirectory)\Output"
      & $cliPath package deploy "$(Build.SourcesDirectory)\Output" "https://cloud.uipath.com/" DefaultTenant -A walmazwnmqbk -I a713bc24-1ef3-4e10-bbdb-6a7594582fea -S s8%0@8bSPKXXefhr --applicationScope "OR.Assets OR.BackgroundTasks OR.Execution OR.Folders OR.Jobs OR.Machines.Read OR.Monitoring OR.Robots.Read OR.Settings.Read OR.TestSetExecutions OR.TestSets OR.TestSetSchedules OR.Users.Read" -o "Test/Sub"